---
title: "Check integrated kernel convergence"
author:
- name: Adam Howes
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    df_print: paged
    code_folding: show
    theme: lumen
abstract: |
  **Task** We check how the convergence of the integrated kernel varies as a function of number of samples per area.
---

# Performing the check

```{r}
type <- "random"
L <- 200
grid <- readRDS("depends/grid.rds")
n <- nrow(grid)
samples <- sf::st_sample(grid, type = type, exact = TRUE, size = rep(L, n))
length(samples) # n * L
sf::st_crs(samples) <- NA
```

Add an `id` column:

```{r}
samples <- st_sf(id = rep(seq_along(1:L), n), geom = samples)

sample_sets <- lapply(seq(10, L, by = 10), function(i) subset(samples, id <= i))
```

Check that the samples look OK:

```{r}
cowplot::plot_grid(
  plot_samples(sample_sets[[1]]),
  plot_samples(sample_sets[[10]]),
  plot_samples(sample_sets[[20]]),
  ncol = 3
)
```

Calculate the Gram matrices:

```{r}
covs <- lapply(sample_sets, adapted_integrated_covariance)

cowplot::plot_grid(
  plot_matrix(covs[[1]]),
  plot_matrix(covs[[10]]),
  plot_matrix(covs[[20]]),
  ncol = 3
)

matrix_comparison <- outer(covs, covs, Vectorize(frobenius))
plot_matrix(matrix_comparison)
```

Perform an experiment with 10, 20 and 50 points versus ground truth 300 points:

```{r}
L_settings <- list(10, 20, 50)
gt_samples <- sf::st_sample(grid, type = type, exact = TRUE, size = rep(300, n))
gt_cov <- adapted_integrated_covariance(gt_samples)
result <- lapply(L_settings, int_convergence_experiment)

names(result) <- c("L_10", "L_20", "L_50")

result <- list_to_df(result) %>%
  pivot_longer(
    cols = 1:3,
    names_to = "L",
    names_prefix= "L_",
    values_to = "value"
  ) %>%
  mutate(L = as.numeric(L))

ggplot(result, aes(x = value)) +
  geom_histogram() +
  facet_grid(~L) +
  labs(x = "Frobenius norm", y = "") +
  theme_minimal()
```

# `functions.R`

```{r, echo=TRUE, eval=FALSE, code=readLines('functions.R')}
```

# Original computing environment

```{r}
sessionInfo()
```
