---
title: "`xbinomial` sampling"
author:
- name: Adam Howes
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_collapsed: yes
    df_print: paged
    code_folding: show
    theme: lumen
abstract: |
  **Task** We test sampling from the custom likelihoods `xbinomial_lpdf` and `xbinomial_logit_lpdf`.
---

# `xbinomial_lpdf`

```{r}
temp1 <- rstan::stan(file = "xbinom.stan", data = list(m = 10, rho = 0.5), warmup = 500, iter = 1000, refresh = 0)
rstan::summary(temp1)$summary
out1 <- rstan::extract(temp1)
plot(out1$y)
hist(out1$y)
```

# `xbinomial_logit_lpdf`

```{r}
temp2 <- rstan::stan(file = "xbinom_logit.stan", data = list(m = 10, eta = 0), warmup = 500, iter = 1000, refresh = 0)
rstan::summary(temp2)$summary
out2 <- rstan::extract(temp2)
plot(out2$y)
hist(out2$y)
```

# Comparison

```{r}
df1 <- data.frame(x = out1$y)
df2 <- data.frame(x = out2$y)

ks.test(out1$y, out2$y)

ggplot() +
  stat_ecdf(data = df1, aes(x = x), geom = "step") +
  stat_ecdf(data = df2, aes(x = x), geom = "step", col = "red")
```

# Stan code

## `xbinom.stan`

```{cpp, echo=TRUE, eval=FALSE, output.var="ex", code=readLines('xbinom.stan')}
```

## `xbinom_logit.stan`

```{cpp, echo=TRUE, eval=FALSE, output.var="ex", code=readLines('xbinom_logit.stan')}
```

# Original computing environment

```{r}
sessionInfo()
```
