# Comparison

```{r}
fit_centroid <- readRDS("centroid.rds")
fit_integrated <- readRDS("integrated.rds")
```

## Sampling speed

```{r}
samples_per_second <- function(fit) {
  # Outside of warm-up phase
  times <- rstan::get_elapsed_time(fit)
  # Number of samples in first chain
  nsim_iter <- fit@stan_args[[1]]$iter
  nsim_iter / mean(times[, 2])
}
samples_per_second(fit_centroid)
samples_per_second(fit_integrated)
```

## Convergence analysis

Trace-plots:

```{r}
bayesplot::mcmc_trace(fit_centroid, pars = "l")
bayesplot::mcmc_trace(fit_centroid, pars = "beta_0")
bayesplot::mcmc_trace(fit_centroid, pars = "rho[28]") # For example
bayesplot::mcmc_trace(fit_integrated, pars = "l")
bayesplot::mcmc_trace(fit_integrated, pars = "beta_0")
bayesplot::mcmc_trace(fit_integrated, pars = "rho[28]")
```

Rank histograms:

```{r}
bayesplot::mcmc_rank_overlay(fit_centroid, pars = "l")
bayesplot::mcmc_rank_overlay(fit_centroid, pars = "beta_0")
bayesplot::mcmc_rank_overlay(fit_centroid, pars = "rho[28]")
bayesplot::mcmc_rank_overlay(fit_integrated, pars = "l")
bayesplot::mcmc_rank_overlay(fit_integrated, pars = "beta_0")
bayesplot::mcmc_rank_overlay(fit_integrated, pars = "rho[28]")
```

All Rhat < 1.1 necessary but not sufficient:

```{r}
which(rstan::summary(fit_centroid)[["summary"]][, "Rhat"] > 1.1)
which(rstan::summary(fit_integrated)[["summary"]][, "Rhat"] > 1.1)
```

Fitted values comparison:

```{r}
fitted_centroid <- summary(fit_centroid)$summary[paste0("rho[", 1:28, "]"), "mean"]
fitted_integrated <- summary(fit_integrated)$summary[paste0("rho[", 1:28, "]"), "mean"]
plot(fitted_centroid, fitted_integrated)
```
